#!/usr/bin/env python3
"""
OrganisationsAI - Quick Start Script
One-command setup for the entire application
"""

import os
import sys
import subprocess
import time
from pathlib import Path
from typing import Optional


class Colors:
    """Terminal colors"""
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'


def print_header(text: str):
    """Print colored header"""
    print(f"\n{Colors.BOLD}{Colors.HEADER}{'='*70}{Colors.ENDC}")
    print(f"{Colors.BOLD}{Colors.HEADER}{text:^70}{Colors.ENDC}")
    print(f"{Colors.BOLD}{Colors.HEADER}{'='*70}{Colors.ENDC}\n")


def print_success(text: str):
    """Print success message"""
    print(f"{Colors.GREEN}[✓]{Colors.ENDC} {text}")


def print_error(text: str):
    """Print error message"""
    print(f"{Colors.RED}[✗]{Colors.ENDC} {text}")


def print_info(text: str):
    """Print info message"""
    print(f"{Colors.BLUE}[→]{Colors.ENDC} {text}")


def print_warning(text: str):
    """Print warning message"""
    print(f"{Colors.YELLOW}[!]{Colors.ENDC} {text}")


def run_command(cmd: list, description: str = "") -> bool:
    """Run shell command"""
    try:
        if description:
            print_info(description)
        
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            print_error(f"Command failed: {' '.join(cmd)}")
            if result.stderr:
                print(f"  Error: {result.stderr[:200]}")
            return False
        
        return True
    
    except Exception as e:
        print_error(f"{e}")
        return False


def quick_start():
    """Run quick start"""
    print_header("OrganisationsAI - Quick Start")
    
    project_root = Path(__file__).parent
    
    # Step 1: Check Python
    print_info("Checking Python version...")
    if sys.version_info < (3, 11):
        print_error(f"Python 3.11+ required (found {sys.version_info.major}.{sys.version_info.minor})")
        return False
    
    print_success(f"Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")
    time.sleep(0.5)
    
    # Step 2: Check virtual environment
    venv_path = project_root / ".venv"
    if not venv_path.exists():
        print_info("Creating virtual environment...")
        if not run_command([sys.executable, "-m", "venv", str(venv_path)]):
            print_error("Failed to create virtual environment")
            return False
        print_success("Virtual environment created")
    else:
        print_success("Virtual environment exists")
    
    time.sleep(0.5)
    
    # Step 3: Determine Python executable in venv
    if sys.platform == "win32":
        python_exe = str(venv_path / "Scripts" / "python.exe")
        pip_exe = str(venv_path / "Scripts" / "pip.exe")
    else:
        python_exe = str(venv_path / "bin" / "python")
        pip_exe = str(venv_path / "bin" / "pip")
    
    # Step 4: Upgrade pip
    print_info("Upgrading pip...")
    if not run_command([pip_exe, "install", "--upgrade", "pip", "setuptools", "wheel"]):
        print_warning("pip upgrade had issues, continuing anyway...")
    else:
        print_success("pip upgraded")
    
    time.sleep(0.5)
    
    # Step 5: Install packages
    requirements = project_root / "requirements.txt"
    if requirements.exists():
        print_info("Installing packages...")
        if not run_command([pip_exe, "install", "-r", str(requirements)]):
            print_error("Failed to install packages")
            return False
        print_success("Packages installed")
    
    time.sleep(0.5)
    
    # Step 6: Create .env if missing
    env_file = project_root / ".env"
    if not env_file.exists():
        print_info("Creating .env file...")
        
        import secrets
        secret_key = secrets.token_urlsafe(32)
        
        env_content = f"""# OrganisationsAI Configuration
# Generated by quick_start.py

# Security
SECRET_KEY={secret_key}
SESSION_TIMEOUT=3600
DEBUG=False

# Database (SQLite by default)
DATABASE_URL=sqlite:///data/database.db
SQLALCHEMY_ECHO=False

# Flask
FLASK_ENV=production
FLASK_DEBUG=0

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=standard

# Features
ENABLE_SCANNER=True
ENABLE_EMAIL=False
ENABLE_CLUSTERING=True

# CORS
CORS_ORIGINS=http://localhost:3000,http://localhost:5000

# Paths
DATA_DIR=./data
LOGS_DIR=./logs
UPLOADS_DIR=./data/uploads

# OCR (Optional)
OCR_ENABLED=False
OCR_LANGUAGE=deu

# AI/ML (Optional)
AI_ENABLED=False
OLLAMA_URL=http://localhost:11434
"""
        
        env_file.write_text(env_content)
        print_success(".env file created")
    else:
        print_success(".env file exists")
    
    time.sleep(0.5)
    
    # Step 7: Initialize database
    print_info("Initializing database...")
    db_code = """
from app.db_config import engine
from app.models import Base
Base.metadata.create_all(bind=engine)
print('[OK] Database initialized')
"""
    if not run_command([python_exe, "-c", db_code]):
        print_warning("Database initialization had issues, continuing anyway...")
    else:
        print_success("Database initialized")
    
    time.sleep(0.5)
    
    # Step 8: Summary
    print_header("✨ Setup Complete!")
    
    print(f"""
{Colors.GREEN}Installation successful!{Colors.ENDC}

Next steps:

  1. Start development server:
     {Colors.CYAN}python main.py{Colors.ENDC}

  2. Open in browser:
     {Colors.CYAN}http://localhost:5000{Colors.ENDC}

  3. Use management CLI:
     {Colors.CYAN}python cli.py help{Colors.ENDC}

  4. Run tests:
     {Colors.CYAN}python cli.py test unit{Colors.ENDC}

Documentation:
  - {Colors.CYAN}README.md{Colors.ENDC} - Project overview
  - {Colors.CYAN}CLI_GUIDE_DE.md{Colors.ENDC} - CLI tools guide
  - {Colors.CYAN}INSTALLATION_GUIDE_DE.md{Colors.ENDC} - Detailed installation
  - {Colors.CYAN}README_COMPLETE.md{Colors.ENDC} - Full documentation

Quick commands:
  • {Colors.CYAN}python cli.py dev run{Colors.ENDC} - Start server
  • {Colors.CYAN}python cli.py test unit{Colors.ENDC} - Run tests
  • {Colors.CYAN}python cli.py db backup{Colors.ENDC} - Backup database
  • {Colors.CYAN}python cli.py dev format{Colors.ENDC} - Format code
  • {Colors.CYAN}python cli.py build docker{Colors.ENDC} - Build Docker image

Need help?
  • {Colors.CYAN}python install_wizard.py{Colors.ENDC} - Full setup wizard
  • {Colors.CYAN}python cli.py help{Colors.ENDC} - CLI documentation

{Colors.GREEN}Happy coding!{Colors.ENDC}
    """)
    
    return True


def main():
    """Main entry point"""
    try:
        success = quick_start()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print(f"\n{Colors.YELLOW}Setup cancelled.{Colors.ENDC}")
        sys.exit(1)
    except Exception as e:
        print_error(f"Unexpected error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
